### ISSUE TITLE
npm test fails without running npm run build

### ISSUE THREAD

**Issue by sejoker** [cloudflare/cf-ui#104]
before [PR](https://github.com/cloudflare/cf-ui/pull/101) was landed, this worked:
* `npm install`
* `npm run bootstrap`
* `npm test`

now we have to run 3 steps before running test:

* `npm install`
* `npm run bootstrap`
* `npm run build`
* `npm test`

I assume it was an intended behavior, on the other hand, we should reflect it in the README and CONTRIBUTING docs. I also think we could move aliasing step outside of the build step and run it within `npm run bootstrap`.

Another note, after running `npm run clean` we need again 2 extra steps before able to run tests:
* `npm run bootstrap`
* `npm run build`
* `npm test`

**Comment by tajo** [comment]
Yea, that's because tests don't use aliasing (or webpack) but they are using symlinks that are created by `npm run bootstrap`. Those point to the main file and not source file. That's why you need to rebuild packages to be 100% consistent.

However, as far as you work on one component and its tests at the time you don't need to rebuild. Only if you are trying update tests let's say for cf-component-link and changing source of cf-util-route-handler. It's quite an edge case. It doesn't even happen with UI components since they don't link each other. I think it makes sense.

> we should reflect it in the README and CONTRIBUTING docs

Yea, it should be updated. You can also see it in `.travis.yml`.

> Another note, after running npm run clean we need again 2 extra steps before able to run tests:

I think it nukes only node_modules, so you you should be fine only with `npm run bootstrap`.

**Comment by sejoker** [comment]
@tajo you are right, `npm run clear && npm run bootstrap && npm run test` works fine.

**Comment by sejoker** [comment]
updated README.md as part of [Yarn migration](https://github.com/cloudflare/cf-ui/pull/114).
