### ISSUE TITLE
cf-builder packages

### ISSUE THREAD

**Issue by tajo** [cloudflare/cf-ui#105]
We don't use them at all, so let's discuss why. They should make our life easier when using cf-components. That means we need to find some common patterns that they could solve:

- do we use similar structure for 80% of tables? If yes, let's update cf-builder-table and use it instead of "cooking" UI out of cf-component-table every single time
- the same for cf-builder-card
- cf-builder-pagination seems pretty general and useful as it is

We should also remove redux / local states and pass everything through props. Devs usually want to have complete control over the state. Also, we are autogenerating a lot of Redux stuff, so this can't really work for us, right?

**Comment by hturan** [comment]
Yeah! Tooootally on board with this.

As they stand, the `-builder` components plain don't work in our apps due to exporting a `connect`-ed component (we get errors like `undefined is not an object (evaluating 'state.cards')`).

If we strip out all `redux` and `react-redux` code and find a way to fully control the card state from props (things like active drawer, etc.), that would be ace 🎉

**Comment by tajo** [comment]
Ok, let's remove redux stuff for the start.

**Comment by koddsson** [comment]
Is there anything stopping us from straight up removing these packages?

**Comment by koddsson** [comment]
I think I can see the value being that there's being less code and it being more "neat" in a way but I'm worried about it being another thing to know.

I haven't heard any complaints about just using the `Card` components so far so maybe just using them is not so bad even tho they are pretty cumbersome?

I dunno, I can go either way but I feel like since it's not solving a immediate problem and adds code to our codebase I feel like we have a change to slim down and just remove it.

**Comment by tajo** [comment]
The redux part should be removed in either way. Builder components impose even more restrictions and will have value once our cf-components are polished and in good shape.

**Comment by koddsson** [comment]
>Builder components impose even more restrictions 

Are there use-cases for this? Any reason why we can't just put these more restrictions into the actual components and remove these builder components?

**Comment by tajo** [comment]
I see components as plain "dumb" set of UI pieces. Builders can add state and abstract some common patterns as pagination. You don't want to add that state handling into cf-component-pagination but also you don't want to reimplement it every single time when you need to use it.

**Comment by koddsson** [comment]
Is there something we are doing here?

**Comment by koddsson** [comment]
I'm going to remove this from the fela migration milestone.

**Comment by manatarms** [comment]
I will deprecate these.
