### ISSUE TITLE
Change baseline to 24px

### ISSUE THREAD

**Issue by jculvey** [cloudflare/cf-ui#148]
Our current baseline is 15px (font-size) * 1.5 (line-height) = 22.5px. This is a sad baseline. We should make it something that works out better mathematically, like 24px.

The work would entail changing the entries in cf-style-const. In addition, add back the line height checks in cf-component-box once the new baseline is established.

**Comment by jwineman** [comment]
Is something design has an opinion about?

**Comment by wyuenho** [comment]
I've always said we should use 16px font size. 15px is just a very very odd choice. It used to work in the past because everything else was derived by crazy SASS math, but this broke in the PostCSS side, and will remain unfixable in Fela unless we can faithfully recreate SASS math. Changing this will make manually resolving some of those crazy math a lot easier so we don't have to derive everything again, and just rely on rem and em literals to do their thing.

**Comment by jculvey** [comment]
@jwineman Definitely they do. I spoke to Philina and it seems like the design folks are discussing this stuff internally. When they come to a decision I'll update the ticket.

@wyuenho totally agree.

**Comment by tajo** [comment]
👍  for 16px font size and 24px base line.
