### ISSUE TITLE
Add TypeScript definition files

### ISSUE THREAD

**Issue by PaulBGD** [cloudflare/cf-ui#5]
TypeScript definition files would allow users of TypeScript, Flow, or any other typed variation of JavaScript have types.

**Comment by thejameskyle** [comment]
TypeScript files don't help non-typescript users, and if we're ever going to use a type system it's going to be Flow.

**Comment by PaulBGD** [comment]
Flow is planning on adding support for TypeScript definiton files [(source)](https://github.com/facebook/flow/issues/7).
You can convert TypeScript definition files to Dart declarations [(source)](https://github.com/jirkadanek/definitely_typed).
For the Java/GWT fans, there's a project that allows you to use TypeScript definition files [(source)](http://www.jsweet.org/).

TypeScript definition files have become somewhat of a standard for typed languages that compile to JavaScript. You don't have to convert your existing project to TypeScript to make definition files either.

**Comment by thejameskyle** [comment]
There's a number of incompatibilities that mean TypeScript won't work for Flow unless there are changes (mostly around nullability). Just discussed this with jeffmo on twitter the other day.

I'm not interested in supporting dart since its not used in the React community. I have yet to see anyone using dart:html.

I'm not going to introduce the burden of maintaining TypeScript definition files to our team.

**Comment by PaulBGD** [comment]
There's a couple crazy people who are using [dart with react](https://github.com/cleandart/react-dart). Thanks for the response.
