### ISSUE TITLE
Jest for testing

### ISSUE THREAD

**Issue by tajo** [cloudflare/cf-ui#73]
The current tests are... slow. Also, [snapshot tests](https://facebook.github.io/jest/docs/snapshot-testing.html) would be great for our use-case (we could cut the size of tests in half). 

So, how do you feel about leaving Karma/assertEqualJSX and using Jest + node.js? Running tests in real browsers is nice but [the speed is everything](https://github.com/facebook/jest/issues/139#issuecomment-229277654).

**Comment by jculvey** [comment]
👍

**Comment by handrews** [comment]
@tajo is there data on how robust these snapshot tests are?  Maintaining screenshot-based tests is frequently a nightmare, but I am not familiar with this tool and it's been a while since I dealt with the problem.  Does it require pixel-perfect comparisons or is there a fuzz factor?

Generally, there is a need for some browser-specific testing but certainly not everything needs to go through a real browser.

**Comment by tajo** [comment]
@henry It's not doing real screenshots and comparing pixels. 

It takes a React Component, renders the HTML markup, saves it and in the next run it compares if the markup is unchanged. So it basically works the same way as our current tests except there is no need to manually write the markup that should be generated.

**Comment by handrews** [comment]
@tajo oh awesome.  I spent years designing QA automation systems and things that seem like screenshot-based tests give me anxiety attacks ;-)  There always seems to be someone who thinks they can make it work... (I've never seen it truly scale successfully)

**Comment by jwineman** [comment]
> There always seems to be someone who thinks they can make it work
Inadvertently describes all software development :)

**Comment by wyuenho** [comment]
I'd love to know how much time we spend in babel and webpack before jumping to the conclusion that karma is slow. Opening a window, sending code to it, opening sockets, running tests inside the browser and sending the results back from the local network, none of these sound very slow to me. Profiling data please.

**Comment by wyuenho** [comment]
To give you some perspective. For backgrid, running 195 tests on 3 browsers (555 total) simultaneously took about 8 seconds.

**Comment by tajo** [comment]
@wyuenho The whole `npm run test` takes 1min 30s (on the latest quad core i7). That's bad.

You are right. The problem is not Karma itself. That part takes about last 10s (although I am sure it could be even better with Jest since Karma doesn't parallelize on the component level).

The problem is the bundling. We have to bundle because we test in browser. If we ditch browser testing and run our tests in node.js/jsdom, there is no bundling needed. You just need to use Babel (takes about 5s) and then you can even do partial rebuilds to make it pretty much instant when making changes.

Am I missing something?

**Comment by wyuenho** [comment]
I also suspect bundling isn't the slowest part, creating a bundle for every test is. Can we move to webpack first, then we can use this [trick](https://github.com/webpack-contrib/karma-webpack#alternative-usage) to create just one giant bundle for all the tests.

**Comment by tajo** [comment]
Well, you can get some idea when running `npm run examples:build:internal`

```js
[15:59:50] Finished 'examplesBuildBundle' after 20 s
``` 

Not sure if webpack is faster than browserify + gulp tasks. Agree that the switch to webpack should definitely precede tests, so we can try.

**Comment by wyuenho** [comment]
So here's my current thought.

1. We can remove the default PhantomJS launcher and develop cf-ui on node 6+ and evergreen browsers to sidestep the need for babel. This should be very easy to do. We can also get a cf-ui account from SauceLab for free since this is an OSS project. This should alleviate our CI problem.
2. Each test file is ran through babel and browserify, and bundled with all of their dependencies now. This need not be the case, we can just extract a vendor bundle of all external deps, and create shallow bundles for the test files. The vendor bundle should only be recreated if the dependencies change (rarely). Webpack excels at this. Afterwards, we can then just include the vendor bundle into the browser with a script tag, and the shallow test bundles with another. This should significantly cut down build time during test runs.
3. Just run the test suite for the package you are developing with `npm run test -- --package cf-whatever --no-istanbul --browsers Chrome`.

P.S. I'd really love to move to ES6 modules to enable downstream projects using Webpack to tree-shake their code. AFAIK, node LTS isn't going to support ES6 modules any time soon, so at least for a year or two, we still have to pass the code through Webpack. In that scenario, the only thing that might slightly speed things up are still Webpack and Jest. In the case of Jest, we might save a couple of seconds but still trading that with test reliability (JSDOM).

**Comment by tajo** [comment]
Done with https://github.com/cloudflare/cf-ui/pull/93
